export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS'
export const FETCH_TASK_NAME = 'FETCH_TASK_NAME'
export const FETCH_TASK_DESCRIPTION = 'FETCH_TASK_DESCRIPTION'
export const FETCH_TASK_YAML = 'FETCH_TASK_YAML'